# Importing necessary modules

In [1]:
import pandas as pd
import yfinance as yf
import datetime as dt

# Picking up relevant Tickers and Company names

Like we did in the News Dataset, we have to pull out the list of top IT companies listed under S&P 500 according to Wikipedia

In [2]:
import pandas as pd
import datetime as dt
import yfinance as yf

# Defining the URL
sp500_link = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"

# Reading tables
tables = pd.read_html(sp500_link)
sp500_df = tables[0]

# Filtering according to 'Information Technology'
it_companies = sp500_df[sp500_df['GICS Sector'] == 'Information Technology']

# Extracting tickers and company names
tickers_df = it_companies[['Symbol', 'Security']]

# Fetching historical stock data
start_date = '2016-02-03'
end_date = dt.date.today()

# Create a list to store data for each security
security_data = []

for index, row in tickers_df.iterrows():
    ticker = row['Symbol']
    company_name = row['Security']
    try:
        stock_data = yf.download(ticker, start=start_date, end=end_date)
        stock_data['Company'] = company_name
        stock_data['Ticker'] = ticker
        security_data.append(stock_data)
    except Exception as e:
        print(f"Failed to fetch data for {company_name} (Ticker: {ticker}) - Error: {e}")

# Concatenate data for all securities into a single DataFrame
all_stock_data = pd.concat(security_data)

# Reset index to have Date, Security, and Ticker as columns
all_stock_data.reset_index(inplace=True)

# Reorder columns and include daily open, close, and adjusted close prices
all_stock_data = all_stock_data[['Company', 'Ticker', 'Date', 'Open', 'Close', 'Adj Close']]

# Sort the DataFrame by Date in descending order
all_stock_data.sort_values(by='Date', ascending=False, inplace=True)

# Print the resulting DataFrame
all_stock_data

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

,Company,Ticker,Date,Open,Close,Adj Close
125439,Zebra Technologies,ZBRA,2023-11-14,209.000000,215.660004,215.660004
66639,Lam Research,LRCX,2023-11-14,691.000000,694.919983,694.919983
78399,NetApp,NTAP,2023-11-14,77.739998,78.699997,78.699997
76439,Motorola Solutions,MSI,2023-11-14,310.220001,312.260010,312.260010
74479,Monolithic Power Systems,MPWR,2023-11-14,523.640015,535.469971,535.469971
...,...,...,...,...,...,...
72520,Monolithic Power Systems,MPWR,2016-02-03,59.480000,58.259998,54.429798
70560,Microsoft,MSFT,2016-02-03,53.250000,52.160000,46.446892
68600,Micron Technology,MU,2016-02-03,10.670000,10.760000,10.592063
66640,Microchip Technology,MCHP,2016-02-03,21.030001,21.160000,18.485577
62720,KLA Corporation,KLAC,2016-02-03,66.589996,66.800003,56.907906

In [3]:
# Saving to csv
all_stock_data.to_csv('stock_prices.csv', index=False)